### ISSUE TITLE
file library.groovy not copied

### ISSUE THREAD

**Issue by unidesigner** [scholrly/neo4django#114]
In subfolder gremlin was not copied after installing with `sudo python setup.py install` to my system-wide packages folder. I had to manually copy it.

**Comment by mhluongo** [comment]
That's annoying- I thought I https://github.com/scholrly/neo4django/blob/master/setup.py#L11 took care of that. Did you download the latest from GitHub or PyPi? Thanks for reporting, this definitely needs to get resolved.

**Comment by mhluongo** [comment]
Confirmed and, I think, fixed the issue. This wasn't a problem for pip-installed versions (AFAIK). Sorry for the inconvenience!

**Comment by unidesigner** [comment]
Thanks for the quick fix! Looking forward to start using neo4django!
