### ISSUE TITLE
Django 1.5 support

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#143]

**Comment by nimrodm** [comment]
When will it be available ?

**Comment by mhluongo** [comment]
The plan is to finish this with the next release (shown above as milestone 0.1.9) which should be out within a month. If I get enough community contribution, it could go out earlier.

This is a great issue to work on for new contributors.

**Comment by nimrodm** [comment]
OK, thanks.

**Comment by mhluongo** [comment]
For anyone interested in getting this closed faster- I've started a campaign to fund the completion of this release, including 1.5+ support. Check it out at https://www.bountysource.com/fundraisers/423-neo4django-0-1-9

**Comment by pqn** [comment]
If I use neo4django right now with Django 1.5.1, what are the incompatibility issues that arise? Is it still usable in some aspects?

**Comment by mhluongo** [comment]
Auth and admin almost certainly won't work, and there's no Python 3 support. I'm not sure beyond that- since we don't have 1.5+ specific tests, I can't say. Anecdotally I know some folks are trying it against 1.5, but I haven't heard back. If you do run it with 1.5.1 I'd love to know any issues you run into.

**Comment by rthuffman** [comment]
The bountysource campaign has closed, is there any other way to contribute?

**Comment by mhluongo** [comment]
Absolutely- I have a Gittip account as well that funds neo4django dev- https://www.gittip.com/mhluongo/ . Thanks for thinking to support the project!

**Comment by ccverg** [comment]
@rthuffman you can also crowdfund bounties on specific issues :) https://www.bountysource.com/trackers/207361-scholrly-neo4django

**Comment by aladagemre** [comment]
any news on this?

**Comment by mhluongo** [comment]
I'll be sprinting on this next week at the Neo4j office- I should have an update by Thursday. This is at the top of my list.

If you have any spare cycles, I could use someone testing against Django 1.5+- user-swappable models and aspects of the admin might not work, but it would be really helpful to know if anything else crops up. @pqn sounded interested but I haven't heard back.

**Comment by pqn** [comment]
I have college apps at the moment, but if time crops up I'll let you know. ;)

**Comment by tonjo** [comment]
For now I can say a simple

```
class Activity(models.NodeModel):
    pass

n=Activity.objects.create(name='myact')
```

gives:

```
 Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/tonjo/venv/tuned/local/lib/python2.7/site-packages/django/db/models/manager.py", line 244, in   __get__
  self.model._meta.object_name,
  AttributeError: Manager isn't available; Activity is abstract
```

But Activity is not abstract.

**Comment by mhluongo** [comment]
A quick update: the entire test suite passes on my machine with Django 1.5.4. I'm working on swappable user models now. After that, I could really use some testers :)

@tonjo I can't replicate the issue you're having... could you `pip freeze` in your venv and share the output?

**Comment by tonjo** [comment]
In github I see there is still   

```
class MyGuy(models.NodeModel):
    name = models.StringProperty()
```

while the failing test was on 

```
    name = models.StringProperty(indexed=True)
```

Anyway, my pip freeze:

```
Django==1.4.8
JPype==0.5.4.2
Pygments==1.6
South==0.7.6
Sphinx==1.1.3
argparse==1.2.1
bpython==0.12
coverage==3.6
decorator==3.4.0
django-braces==0.2.1
django-debug-toolbar==0.9.4
django-discover-runner==0.2.2
django-dynamic-fixture==1.6.5
django-email-usernames==1.0
django-localflavor-it==1.0
django-model-utils==1.1.0
docutils==0.10
httplib2==0.8
logutils==0.3.3
lucene-querybuilder==0.1.6
lxml==3.2.3
-e git+https://github.com/scholrly/neo4django.git@88e359d4141a760e67d9313c6f10875ad16a3077#egg=neo4django-dev
neo4jrestclient==1.8.0
nose==1.3.0
nose-regression==1.0
pudb==2013.1
python-dateutil==2.1
python-whois==0.2
six==1.3.0
urwid==1.1.1
wsgiref==0.1.2
```

**Comment by mhluongo** [comment]
@tonjo So- you aren't testing against Django 1.5? When did you have the "Activity is abstract" error? I realize you have another test you're having trouble with, but that's a different issue (this is about Django 1.5 support).

**Comment by tonjo** [comment]
Yes, sorry, wrong issue I'm talking about.
s/1.4.8/1.5.4/g

I got back to 1.4.8 or I couldn't go on,
the failing 1.5 test has exactly the same environment but with Django 1.5.4.
Sorry again, in Italy it's half past midnight ;)

**Comment by mhluongo** [comment]
Heh I understand. I just replicated the other issue, but I'm not seeing any against 1.5 :)

**Comment by tonjo** [comment]
Reinstalled now all the enviroment but I got the same "Activity is abstract" error.
Question: Are `#egg=neo4django` and `#egg=neo4django-dev` the same package?

**Comment by mhluongo** [comment]
re: the "egg" command line argument - They _are_ the same package- the distinction has to do with the versioning within the environment, not the source package version.

Hm, I can't replicate the "abstract" error at all. What happens when you run the test suite (`export DJANGO_SETTINGS_MODULE=neo4django.tests.test_settings; nosetests --with-regression neo4django/tests/`)? Travis has no regressions (https://travis-ci.org/mhluongo/neo4django/jobs/12074100), so if you do, I'd still think it's an environment difference..

**Comment by tonjo** [comment]
I'm happy to say it was not an environment's issue, but my fault.
I left an `abstract=True` on a mixin which derived from object, giving all the children the abstract status.
Seems good now for me, I still have some issues, but not related to 1.5.4 I'm using now.

**Comment by mhluongo** [comment]
_shwew_, excellent!

Everyone please feel free to use Django 1.5 with HEAD. I'm still working on swappable `User` support (and need to further test the admin site), but the bulk of the library works with 1.5.

**Comment by tonjo** [comment]
Now I'm wondering why I didn't have the same errors with 1.4.8, some behavior changes?

Note:

```
[cut]/neo4django/db/models/query.py:54: DeprecationWarning: object.__init__() takes no parameters
super(Condition, self).__init__(*args, **kwargs)
```

**Comment by mhluongo** [comment]
Yeah, I'm familiar with that deprecation warning- it should probably be raised as an issue, though it's not high priority.

**Comment by mhluongo** [comment]
I'm closing this issue- it's been a month since swappable user model support and it looks like the minor issues have been ironed out.

**Comment by tonjo** [comment]
I don't agree ;)
Aren't you forgetting pull request #217 ?
Without it, wrong User model is returned...

**Comment by mhluongo** [comment]
Absolutely right @tonjo, merging it in.

**Comment by mhluongo** [comment]
Taken care of. Anyone else have objections to closing this / outstanding issues with 1.5?
