### ISSUE TITLE
Error in retrieving logged-in user via NodeModelBackend

### ISSUE THREAD

**Issue by bhcarpenter** [scholrly/neo4django#152]
Steps to duplicate:
- Log a user in
- On any subsequent requests, any attempt to resolve the lazy user object into an actual User results in _**\* AttributeError: AttributeError("type object 'User' has no attribute 'user_id'",)_ 

For example: `self.request.user.is_authenticated()` in a view

**Comment by bhcarpenter** [comment]
@mhluongo there is a simple fix, but if you don't mind I'd like to go ahead and go through the motions of writing a test for it and submitting a pull request. I'd like to get up to speed with Python testing tools.

**Comment by bhcarpenter** [comment]
One issue with this approach:

A person could log in and then be authenticated as a different User if the User they logged in as was deleted and then the ID that was saved in session was re-used for a different User by Neo4j. Thoughts?

**Comment by mhluongo** [comment]
Regarding id reuse- ids won't be reused in Neo4j. Still, I'd rather rely on our own identifier than one based on Neo4j internals (they consider ids an implementation detail). Alternatively, we could just add a `user_id` AutoProperty. I'll give that a try.

**Comment by mohamedturki** [comment]
I added `user_id = AutoProperty(indexed=True, unique=True)` and it works fine.

**Comment by mhluongo** [comment]
`user_id` in now in master. Thanks @bhcarpenter and @mohamedturki :)

**Comment by bhcarpenter** [comment]
If we go this route, we'll need to make sure that Django writes `user_id` to session instead of the primary key, or flag the `user_id` as the primary key.

**Comment by mhluongo** [comment]
Continuing our off-GitHub discussion- are you sure this is an issue? Initial testing seems to properly store the user in-session, regardless of this change. LMK if you can confirm otherwise.

**Comment by mhluongo** [comment]
@bhcarpenter are you still having a problem with this?

**Comment by bhcarpenter** [comment]
I haven't had a chance to check it yet, but I'm planning on it tonight. I'm worried that the success you've seen might be coincidental due to the user_id being equal to the primary key, so I'm going to try to test it when user_id != primary key tonight.

**Comment by bhcarpenter** [comment]
Confirmed that this breaks if user_id is not equal to the node id. We need to make sure that Django stores user_id in session instead of the node id.

**Comment by bhcarpenter** [comment]
I'm pretty new to Django internals, but https://github.com/django/django/blob/stable/1.4.x/django/contrib/auth/__init__.py#L72 seems to imply that we have to work with the actual `id` property of the user objects.

Maybe we can have the `authenticate` method of `NodeModelBackend` return an adapter that subclasses `neo4django.auth.User` and overrides the `id` property accessor to return `user_id` instead?

**Comment by mhluongo** [comment]
@bhcarpenter I read that as "`user.id` needs to be unique" to be properly stored in the session and prevent collisions- which it is, since no `NodeModel` instance shares an id with another. Let me look into this a bit, but if `id` really needs to point to `user_id` I'd rather implement the `primary_key=True` method (https://docs.djangoproject.com/en/dev/ref/models/fields/#primary-key)  and set `user_id` as the primary so `id` points to it.

**Comment by bhcarpenter** [comment]
Take a look at that line of the Django source that I referenced. I don't see any way around aliasing the `id` property to return `user_id`. Also, from what I can read of the docs, setting `primary_key=True` just tells Django not to automatically generate an `id` property. It doesn't seem to automatically point `id` to the primary key.

Technically, I think django.contrib.auth should be using `pk` instead of `id`, but since it isn't....

Are we dead set on having a custom `user_id` field instead of using `id`? I'm worried that we're also going to break compatibility with third-party plugins like django_social_auth, etc.

**Comment by mhluongo** [comment]
Good point, you're right about primary_key. I wish it did work that way though :(

The custom user_id is for migrations / backups / etc- node ids are supposed to be considered an implementation detail. Maybe that doesn't matter so much, though, since we already have a unique `username` field?

I also wonder how this all involves Django 1.5's swappable `User` models (#143).
