### ISSUE TITLE
Database Router breaks functionality

### ISSUE THREAD

**Issue by szabi** [scholrly/neo4django#156]
Hi,

I was trying to set up the example form https://neo4django.readthedocs.org/en/latest/getting-started.html and https://neo4django.readthedocs.org/en/latest/writing-models.html

I encountered the following problem:
when the recommended (so that it plays nicely with sqlite3 data)

``` python
DATABASE_ROUTERS = ['neo4django.utils.Neo4djangoIntegrationRouter']
```

is set, I get the error:

```
AttributeError: type object 'Model' has no attribute '__metaclass__'
```

when trying either `python manage.py syncdb` or `python manage.py shell`.

When deleting the DATABASE_ROUTERS entry I do not get the error.

**Comment by szabi** [comment]
Actually, as soon as I add the line `from neo4django.db import models` to a models.py, I get the very same error
(`AttributeError: type object 'Model' has no attribute '__metaclass__'`)

**Comment by stephendwolff** [comment]
are you using django 1.4 or 1.5? i don't think 1.5 is supported yet..

Sent from Samsung Mobileszabi notifications@github.com wrote:Actually, as soon as I add the line from neo4django.db import models to a models.py, I get the very same error
(AttributeError: type object 'Model' has no attribute '**metaclass**')

**Comment by mhluongo** [comment]
Absolutely right- check out https://github.com/scholrly/neo4django/issues/143 & https://github.com/scholrly/neo4django/issues/149 for more info. Django 1.5 support is planned for the next release, and is a great place to contribute if anyone is interested :)

**Comment by szabi** [comment]
Ok, sorry, you are right, I'm on 1.5. Should have checked compatibility notes. Also sorry for not noticing #149, probably because it was already closed. sry for the inconvenience, if any was caused.

**Comment by mhluongo** [comment]
Closing this. No worries :)

**Comment by mhluongo** [comment]
Folks- I've started a campaign to fund the completion of this release, including [Django 1.5+ support](https://github.com/scholrly/neo4django/issues/143). Check it out at https://www.bountysource.com/fundraisers/423-neo4django-0-1-9
