### ISSUE TITLE
Wrong queries sent to neo4j server when using auth module

### ISSUE THREAD

**Issue by lutoma** [scholrly/neo4django#182]
I just started playing around with the neo4django.auth module and after successfully adding my user (Which I can also view in the neo4j web frontend, so the node exists), I got the following error when trying to log in:

```
Exception Value:    'unicode' object has no attribute '_list'
Exception Location: […]/lib/python2.7/site-packages/neo4django-0.1.8-py2.7.egg/neo4django/db/models/query.py in execute, line 1124
```

After playing around for a bit and adding a `print("result set: {}".format(raw_result_set))` right after line 1119 in neo4django/db/models/query.py I found out that raw_result_set is, in fact, an unicode object, apparently containing neo4j errors about incorrect queries:

```
result set: javax.script.ScriptException: Unclosed parenthesis
"START typeNode=node({typeNodeId}),n=node({startParam}) WHERE (n.username! =  "lutoma")"
                                                                     ^
result set: javax.script.ScriptException: Unclosed parenthesis
"START typeNode=node({typeNodeId}),n=node({startParam}) WHERE (n.username! = "lutoma")"
                                                                     ^
result set: javax.script.ScriptException: string matching regex `\z' expected but `;' found
Unfortunately, you have run into a syntax error that we don't have a nice message for.
By sending the query that produced this error to cypher@neo4j.org, you'll save the puppies and get better error messages in our next release.

Thank you, the Neo4j Team.
result set: javax.script.ScriptException: Unclosed parenthesis
"START typeNode=node({typeNodeId}),n=node({startParam}) WHERE (n.username! = "lutoma")"
                                                                     ^
result set: javax.script.ScriptException: Unclosed parenthesis
"START typeNode=node({typeNodeId}),n=node({startParam}) WHERE (n.username! = "lutoma")"
```

I'm using the master git branch from the neo4django repo with Django 1.4.5, lucene-querybuilder 0.1.6 and neo4jrestclient 1.9.0.

**Comment by mhluongo** [comment]
Hm, do you have a code snippet to reproduce this? It works fine on my end (I can log into admin, etc). Also, what version of Neo4j are you using?

**Comment by mhluongo** [comment]
Oh, and if you're alright doing a bit more debugging, the line in `execute()` just before that one has `groovy` and `params` variables- the values of both of those would be really handy.

**Comment by lutoma** [comment]
Turns out I've been using neo4j 1.6 for whatever reason which was why everything broke. Switched to neo4j 1.9 and now it works fine.

**Comment by mhluongo** [comment]
Excellent, let me know if you run into anything else!
