### ISSUE TITLE
tastypie doesn't work with neo4django

### ISSUE THREAD

**Issue by lutoma** [scholrly/neo4django#184]
I'm currently building a backend for an iPhone app using neo4django and am trying to use tastypie with it.

I have a neo4django model like this in my models.py:

``` python

class Post(models.NodeModel):
    user = models.Relationship(User, rel_type = 'posted_by',
        related_name = 'user')

    description = models.StringProperty()
    is_reshare = models.BooleanProperty()

    [more properties]

    def __unicode__(self):
        return 'Post from {} by {}'.format(self.created,
            self.user.username)
```

Unfortunately, as soon as I add some tastypie API resource like the following:

``` python
class PostResource(ModelResource):
    class Meta:
        queryset = Post.objects.all()
        resource_name = 'post'
```

and call `PostResource()` to initialize a new object of that resource somewhere, it results in the following traceback:

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/admin/posts/post/

Django Version: 1.4.4
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'south',
 'neo4django',
 'neo4django.auth',
 'tastypie',
 'posts')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')


Traceback:
File "[…]/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  101.                             request.path_info)
File "[…]/lib/python2.7/site-packages/django/core/urlresolvers.py" in resolve
  298.             for pattern in self.url_patterns:
File "[…]/lib/python2.7/site-packages/django/core/urlresolvers.py" in url_patterns
  328.         patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
File "[…]/lib/python2.7/site-packages/django/core/urlresolvers.py" in urlconf_module
  323.             self._urlconf_module = import_module(self.urlconf_name)
File "[…]/lib/python2.7/site-packages/django/utils/importlib.py" in import_module
  35.     __import__(name)
File "[…]/[project_name]/urls.py" in <module>
  6. from posts.api import PostResource
File "[…]/posts/api.py" in <module>
  6. class PostResource(ModelResource):
File "[…]/lib/python2.7/site-packages/tastypie/resources.py" in __new__
  1762.         new_class.base_fields.update(new_class.get_fields(include_fields, excludes))
File "[…]/lib/python2.7/site-packages/tastypie/resources.py" in get_fields
  1859.             api_field_class = cls.api_field_from_django_field(f)
File "[…]/lib/python2.7/site-packages/tastypie/resources.py" in api_field_from_django_field
  1804.         internal_type = f.get_internal_type()
File "[…]/lib/python2.7/site-packages/neo4django/utils.py" in __getattr__
  303.         return getattr(target, name)

Exception Type: AttributeError at /admin/posts/post/
Exception Value: 'super' object has no attribute 'get_internal_type'
```

I've dug around in the Django documentation, [which says](https://docs.djangoproject.com/en/dev/howto/custom-model-fields/#django.db.models.Field.get_internal_type) that `get_internal_type` usually is part of the `Field` class, but can be overriden by custom model fields.

So I tried adding a `get_internal_function` to the `Property` class in `properties.py`:

``` python
def get_internal_type(self):
    print("get_internal_type")
    return 'Neo4jField'
```

This function _does_ get called, however the same function still seems to be missing / needs to be routed somewhere else as I'm still getting the same exception.

Besides the `get_internal_type` function, there also seem to be missing some variables called `null` and `help_text` in the Property classes or somewhere.

As for versions, the ouput of `pip freeze` in my virtualenv is

```
Django==1.4.4
South==0.8.1
decorator==3.4.0
django-tastypie==0.9.15
httplib2==0.8
lucene-querybuilder==0.1.6
mimeparse==0.1.3
neo4django==0.1.8
neo4jrestclient==1.9.0
python-dateutil==2.1
six==1.3.0
uuid==1.30
wsgiref==0.1.2
```

and as before I'm using neo4j 1.9.

**Comment by mhluongo** [comment]
Sorry- unfortunately, I can't test against every popular Django app :(. In fact, until the recent admin integration I wasn't sure whether we'd ever approach integration with third-party apps. I'd love to see neo4django working with tastypie.

The reason you're seeing issues is that the legacy codebase neo4django is built on introduced a separate `Property` class for model definition magic, and `BoundProperty` class for properties that are bound to a particular model class post definition, versus Django proper's one `Field` class. Since that hasn't been refactored (yet!), you also need to add 'get_internal_function' to the list of routed attributes in `BoundProperty.__init__()`.

**Comment by lutoma** [comment]
I just played around with it and got tastypie to work with neo4j: https://github.com/lutoma/neo4django/commit/81d8dfc8d8b4a24597ae50171428bbcab24841d3

Unfortunately all Relationships end up in the API json as a string representation of the RelationshipInstance object: `"location": "<neo4django.db.models.relationships.RelationshipInstance object at 0x7f3c1002e110>",`. I'll have to see how I can fix it to also represent those properly.

**Comment by mhluongo** [comment]
Does it work for the single side of one-to-many relationships? I would think it might in that case.

**Comment by lutoma** [comment]
Hmm, kind of. But it also contains a string representation of the object instead of the object itself in json form. Also, the key is wrong (It's "location" while it should be "post". The object currently viewed is a Location object).

``` json
{"id": 4544, "lat": "0", "location": "Post from 2013-06-07 13:36:47.490858-04:00 …", "lon": "0", "resource_uri": "/api/location/4544/", "verbose_name": "Mannheim, Europe"}
```

**Comment by lutoma** [comment]
Okay, I think I found out why this is happening. My patch lets Relationship objects return `Neo4jRelationship` as internal_type. Tastypie uses `get_internal_type` to figure out how to handle objects, and the default for unknown types is `CharField`: https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L1797

I'm not to sure about how they handle ForeignKeys though since the Code about them seems to be commented out. I'll dig a little further in the Tastypie codebase

**Comment by mhluongo** [comment]
@lutoma is this closed out, or should it stay open?

**Comment by pirhoo** [comment]
Hi guys,

neo4django works just fine with Tastypie, thanks for what you already done! I just met an issue with complex filters (such as `contains`, `startswith`, etc) that throw me this exception :

> argument of type 'NoneType' is not iterable

I'm not a Tastypie expert but I tried to query neo4j with `MyModel.objects.filter(name__contains='test')` and it worked...

Any idea?

All the best!

**Comment by mhluongo** [comment]
@Pirhoo I'm not a Tastypie expert either :) - any chance you could post code to replicate this? @lutoma might have some thoughts as well.

**Comment by pirhoo** [comment]
Sure :)

My model:

``` python
class Project(models.NodeModel):
    name = models.StringProperty()
    source = models.URLProperty()
    image = models.URLProperty()
    started = models.DateTimeProperty()
    comment = models.StringProperty()
    ended = models.DateTimeProperty()
    twitterHandle = models.StringProperty(verbose_name="Twitter Handle")
    activityin = models.Relationship("Country",rel_type='hasActivityIn')
    owner = models.Relationship("Organization",rel_type='hasOwner')
    commentary = models.Relationship("Commentary",rel_type='hasCommentary')
    partner = models.Relationship("Organization",rel_type='hasPartner')
    def __unicode__(self):
        return self.name
```

Its resource:

``` python
class ProjectResource(ModelResource):
    class Meta:
        queryset = Project.objects.all()      
        allowed_methods = ['get'] 
```

The CURL request, **GET** method to http://d:8000/api/v1/organization/?name__contains=ABZV :

```
curl 'http://d:8000/api/v1/organization/?name__contains=ABZV' -H 'Accept: application/json,text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' -H 'Connection: keep-alive' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Host: d:8000' -H 'Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/28.0.1500.52 Chrome/28.0.1500.52 Safari/537.36' -H 'Cache-Control: max-age=0' --compressed
```

Cheers!

**Comment by nikolasd** [comment]
Has anyone accomplished to make a fully working tastypie/neo4django resource/model with full CRUD operations?

**Comment by pirhoo** [comment]
Yes but I had to use my own ModelResource class to patch some bugs:
https://github.com/jplusplus/detective.io/blob/master/app/detective/individual.py

**Comment by skyleronken** [comment]
Mind outlining what specifically had to be changed/overridden to make everything play nice?

**Comment by mhluongo** [comment]
:+1: I think a blog post would really help here. @Pirhoo, @lutoma or anyone else using tastypie + neo4django already, would one of you be interested? We could also add a tastypie section to the docs.

**Comment by pirhoo** [comment]
Hi guys,

As suggested by @skyleronken) by email, I'll be happy to create a generic _ModelRessource_ class that you could use ! In my case, the _IndividualRessource_ I created is very particular : it allows us to create an API on-the-fly and generate relationships fields automatically. It not perfect but it works. 

For writing data, the magic intervenes firstly into the _hydrate_m2m_ method :
https://github.com/jplusplus/detective.io/blob/master/app/detective/individual.py#L265
In this method I convert the received relationships into a list of objects that we can save with neo4django. 

Later, with the _save_m2m_ method, I use the list I created to add relationships to the current entity. 
https://github.com/jplusplus/detective.io/blob/master/app/detective/individual.py#L293 

Tell me if that helps!

**Comment by skyleronken** [comment]
Looking forward to @Pirhoo's post.

In the mean time, I stumbled upon the cause of my issue. I kept getting this error when trying to read data from some of my resources:

'RelationshipInstance' object has no attribute 'pk'

I discovered the issue was related to using a ToOneField in my Tastypie ModelResource definition. Once I changed it to ToManyField I no longer had the problem. Although this isn't preferable, its at least operable. I am not familiar enough with the codebase of either of the frameworks to say for sure why the issue exists. However, I believe it is probably something to do with how Neo4Django doesn't differentiate between a OneToOne and OneToMany relationship. Meanwhile Tastypie's lookups behave differently based on the anticipated cardinality as defined in the modelresource.

Hope that helps!

**Comment by pirhoo** [comment]
If the cardinality is painless, a solution could be to register the field as ToManyField in tastypie, then hydate the field to ensure that it has only one relationship. 

http://django-tastypie.readthedocs.org/en/latest/resources.html#hydrate-foo

**Comment by mlent** [comment]
@Pirhoo, If you are still having issues with the 'contains' relationships, take a look at the modification we've made to Tastypie itself to deal with this issue:

https://github.com/mlent/django-tastypie/commit/9ce920d2acca06c52bcd7bc759f78190ba317ba4

For us, it solved the problem of passing in __contains and __endswith filters. For example, a query such as follows works:

http://localhost:8000/api/sentence/?format=json&tense=fut&voice=act&mood=ind&lemma__endswith=πω

**Comment by pirhoo** [comment]
@mlent great, thanks! Do you plan to pull-request it to Tastypie or is it too specific to neo4django ?

**Comment by mlent** [comment]
@Pirhoo From the looks of it, Tastypie has almost 200 open pull requests, so I don't know if there's any point. I hadn't planned to make a pull request, because I haven't/won't bother testing whether it works outside neo4django.

**Comment by pirhoo** [comment]
@mlent agree.

As I said before, I overloaded  the ModelResource class:
https://github.com/jplusplus/detective.io/blob/master/app/detective/individual.py#L76

It might be good to put your patch in a sub-class instead of changing Tastypie directly, don't you think?

**Comment by mlent** [comment]
@Pirhoo Yeah, probably makes sense. We're going to cut the neo4django dependency though, as it appears that using it is causing our queries to take an extraordinarily long time for some reason, particularly when paired with Tastypie. I'm not responsible for the back end of this project though, so I can't say why this is the case exactly.
