### ISSUE TITLE
RelationshipInstance.create()

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#195]

**Comment by mhluongo** [comment]
Ah, this is actually already implemented.

**Comment by tonjo** [comment]
Uhm, actually, having the relationship friends, if I do
bill.friends.create(name='jim')
it will create a Person named jim, but NOT related to bill
(not as a bill's friend).

**Comment by mhluongo** [comment]
@tonjo thanks, I'll check the tests for this tonight.
