### ISSUE TITLE
relationship-spanning lookups

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#20]
Like in the Django docs -> https://docs.djangoproject.com/en/dev/topics/db/queries/#lookups-that-span-relationships

This is another way to do simple traversals in a familiar way for Django devs.

**Comment by mhluongo** [comment]
Some of this work is going to look very familiar to select_related, and can definitely reuse code. Some of this work might require a re-write of query execution with Gremlin or Cypher... =/

On the plus side, said re-write would enable whittling the number of requests query execution takes even further.

**Comment by davemt** [comment]
Relationship-spanning lookups should throw proper errors until this issue is resolved.

This raises an exception, but a misleading one:

```
ModelA.objects.filter(model_b__my_property=[...])
```

This does not raise any exceptions and simply returns an empty result set:

```
ModelA.objects.filter(model_b__in=[...])
```

**Comment by mhluongo** [comment]
@d10genes if filter() ends up being easy, you could totally take a similar approach with this- given it's out of scope of the neo4django tutorial. Let me know if you're interested.
