### ISSUE TITLE
Failed to querying Neo4J

### ISSUE THREAD

**Issue by pirhoo** [scholrly/neo4django#200]
Hi guys,

I failed systemically to querying Neo4J using the models done with neo4django. The following code returns an error 400 (from java?) :

``` python```
pete = Person.objects.create(name='Pete', age=30)
pete.save()
```

Throws a Java exception:

```
Invalid data sent: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method removeProperty() on null object
```

Here the compele log:
http://dpaste.com/1292606/

I'm on Ubuntu 13.04 and I took care to install python-jpype (don't know if it's necessary). Also, I succeed to use [neo4j-rest-client](https://github.com/versae/neo4j-rest-client) without any problem with my local neo4j instance.

Any idea?
Best

**Comment by pirhoo** [comment]
My bad, I was using Neo4J **1.9** ! Cheers !

**Comment by mhluongo** [comment]
Thanks! And for the record, you don't need jpype, since everything is over REST.

**Comment by pirhoo** [comment]
Understood. Thanks!
