### ISSUE TITLE
Creating a node with .objects.create(id=SOME_ID) overwrite existing node

### ISSUE THREAD

**Issue by tonjo** [scholrly/neo4django#201]
I don't actually see a reason for creating a Node giving the id, 
but definitely it shouldn't overwrite the node.
It's not a real substitution, the previous relationships are still there,
but if the new node is from another class the result is very strange.
(I have a Person with the characteristics of a Shop, for example).

**Comment by mhluongo** [comment]
Oh, that is a very strange case. `objects.create(id=<SOME ID>)` _should_ throw an error, since you can never manually specify a node id in Neo4j. It will need to be a special case.
