### ISSUE TITLE
Python 3.x incompatibility

### ISSUE THREAD

**Issue by torbjoernk** [scholrly/neo4django#236]
It should be stated somewhere, that neo4django is not compatible with Python 3.x.

I had to learn it the hard way, while getting import exceptions in `neo4jclient.py` [1] and finally I gave up on `rest_utils.py` [2].

Are you planning or working on Python 3.x support? I'm not sure, whether I can help porting it.

1: 

```
File "neo4django/neo4jclient.py", line 1, in <module>
    from urlparse import urlparse
ImportError: No module named 'urlparse'
```

Should be imported as `from urllib.parse import urlparse`.

2:

```
File "neo4django/rest_utils.py", line 2, in <module>
    from itertools import izip_longest, chain, ifilter
ImportError: cannot import name izip_longest
```

`izip_longest` might be renamed into `zip_longest` but there is no function `filter` in Python3's `itertools` module.

**Comment by mhluongo** [comment]
@torbjoernk I would love Python 3 support, but I'm struggling to keep up with Django and Neo4j right now. I'd definitely appreciate the contribution if you did have some time.

**Comment by mhluongo** [comment]
Closing this in favor of #260. Let's make neo4django Py3k compatible!
