### ISSUE TITLE
Django 1.7.1 support?

### ISSUE THREAD

**Issue by mvillarejo** [scholrly/neo4django#255]
Hello, are you planning to support Django 1.7.1 anytime soon? 
Thanks and congratulations!

**Comment by mhluongo** [comment]
No active plans, but we'd appreciate any related PRs!

**Comment by icotoi** [comment]
Any news on this?

**Comment by casraz** [comment]
searching all over the place for this; any news? Django 1.5 is outdated and not supported anymore. 1.6 or 1.7 support would be very useful. Any news?

**Comment by mhluongo** [comment]
Unfortunately, I've moved on to other projects and don't have time to
update the library to the latest version of Django. However, PRs are
welcome and I'm happy to advise anyone interested in giving it a shot.

## 

Matt Luongo
Software Developer
about.me/luongo

**Comment by casraz** [comment]
could you recommend a good alternative?

**Comment by mhluongo** [comment]
There are a [number of options](http://neo4j.com/developer/python/).

**Comment by avneesh91** [comment]
Hi, I'd like to try this out. Could you tell me where to start?

Thanks,
Avneesh

**Comment by auvipy** [comment]
this is a good alternative. https://github.com/robinedwards/neomodel

but I will try to send PR regarding django 1.7/1.8/1.9+ support for this library

**Comment by mvillarejo** [comment]
Thanks auvipy.

this can be closed now as it no longer applies
