### ISSUE TITLE
Bare objects.all() queries throw an AttributeError

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#27]
```
class C(models.NodeModel):
    pass

>>> [C.objects.create() for i in xrange(2)]
[<C: C object>, <C: C object>]
>>> list(C.objects.all())
[<C: C object>, <C: C object>]
>>> C.objects.all()
AttributeError: 'Query' object has no attribute 'set_limits'
```

**Comment by mhluongo** [comment]
I think this comes up so frequently using an interpreter interactively because it's a problem with `__str__`...

**Comment by necaris** [comment]
Comes up for me with objects.filter() and objects.get() as well -- much more general!

**Comment by mhluongo** [comment]
@necaris, I can confirm the issue with filter(), but not get(). Should have a fix soon.

**Comment by mhluongo** [comment]
For posterity - the underlying issue was slicing `NodeQuerySet`s- `QuerySet.__repr__()` returns a slice, which required calling `set_limits()` on the internal `Query`.
