### ISSUE TITLE
transaction

### ISSUE THREAD

**Issue by mgom** [scholrly/neo4django#50]
Can we do transaction with neo4django ?

**Comment by mhluongo** [comment]
Not explicitly, but object updates are tied to transactions, and  get_or_create and other queryset actions will be soon. What's the use case?

**Comment by mgom** [comment]
thx
my case : i want to create or/and update several nodes in the same
transaction

On Mon, Feb 13, 2012 at 5:29 PM, Matt Luongo <
reply@reply.github.com

**Comment by mhluongo** [comment]
Interesting.. let me think about this a bit, it sounds like a compelling use case. In vanilla Django, how would you accomplish this- explicit transaction management? Or is there another, more Django-friendly way? Also, what sort of conditions do you have- index-based or structural?

**Comment by mhluongo** [comment]
If this is an important one-off, you can call you own Groovy/Gremlin code, auto-wrapped in a transaction, using `neo4django.db.connection.gremlin_tx(gremlin_script)`. As long as the return value if a node iterable, you can then construct  neo4django models from it using `YourModel._neo4j_instance(rest_node)`. I know this might be a bit more work than you'd like, but it should work until more formal, user-friendly transactions are possible.

**Comment by mhluongo** [comment]
Note that this method doesn't use the REST client's 'transactional' (aka batch) support, so it's much more flexible. Any exceptions thrown in your Groovy/Gremlin will roll the transaction back.

**Comment by mgom** [comment]
thx Matt
i will see that

On Wed, Feb 15, 2012 at 5:26 PM, Matt Luongo <
reply@reply.github.com

**Comment by mhluongo** [comment]
Closing this, let me know if you have any other questions- I'll update the status via related issues.
