### ISSUE TITLE
uniqueness error does not display the correct property name

### ISSUE THREAD

**Issue by baconz** [scholrly/neo4django#62]
The uniqueness error:

```
"Duplicate index entries for <%s>.%s"
```

Does not display the correct property name, it displays the last property name that was looped through when the script was built.

**Comment by mhluongo** [comment]
@baconz I'm writing a test to confirm this, and then hopefully fix it. I understood when you raised the issue, but I seem to have forgotten- is the problem related to inheritance?

**Comment by baconz** [comment]
Shoot -- it has been a long time for me too (I should have included a test case...). Looking at the code, I don't think the issue is related to inheritance -- that error is raised outside of the `for key, prop` loop, and so if it is raised, the name that gets subbed in (`prop.name`) is just the last prop that was looped through. Make sense?

**Comment by mhluongo** [comment]
Yeah, I think so- it shouldn't be hard to come up with a test case for that. Thanks :)

By the by, I'm shooting you an email about this maintenance release & future plans. I want to get some feedback from your team, if you guys have a moment.

**Comment by baconz** [comment]
Sounds great!
