### ISSUE TITLE
memoized _type_node causes problems in test runs 

### ISSUE THREAD

**Issue by baconz** [scholrly/neo4django#73]
Since the _type_node gets memoized, when cleandb wipes it out in between test runs, we sometimes end up referencing a type node that does not exist in our queries.

**Comment by mhluongo** [comment]
Hm, I thought I had come up with a solution for this already- investigating.

**Comment by mhluongo** [comment]
Ah, I see, you need more than just checking for DEBUG, like in [base.py](https://github.com/scholrly/neo4django/blob/278400647ae6e78c215455ce19a54f7eca5904f5/neo4django/db/models/base.py#L395) right now?
