### ISSUE TITLE
choices.all() repr 

### ISSUE THREAD

**Issue by wcbeard** [scholrly/neo4django#81]
Going through the Django tutorial, I get a poll object with
`p = Poll.objects.get(pk=3)`. It's related to the Choice class, which includes

class Choice(models.NodeModel):
    poll = models.Relationship(Poll,
                                rel_type=neo4django.Incoming.OWNS,
                                single=True,
                                related_name='choices')

While there aren't any choice model instances associated with this poll object, calling the choices.all method gives

> > > p.choices.all()
> > > <neo4django.db.models.relationships.RelationshipQuerySet at 0xad8efcc>

Wrapping it in a list gives what you'd expect

> > > list(p.choices.all())
> > > []

**Comment by mhluongo** [comment]
Hm, looks like this was closed by pull request #106.
