### ISSUE TITLE
neo4django.tests.property_tests.test_array_property_validator regression

### ISSUE THREAD

**Issue by mhluongo** [scholrly/neo4django#85]

**Comment by doismellburning** [comment]
Ah phew, thought I'd broken something with Travis!

**Comment by mhluongo** [comment]
Nope, I think you're good on this! The weird thing is test_select_related- I can't confirm, but I have another user who's seen it too...

**Comment by mhluongo** [comment]
@d10genes are you still interested in working on this? It should be a quick-ish fix.

**Comment by wcbeard** [comment]
@mhluongo I'll look at it, thanks for reminding me.

**Comment by mhluongo** [comment]
Actually @d10genes I've got this.
