### ISSUE TITLE
Gremlin not included in packages (can't find library.groovy at runtime)

### ISSUE THREAD

**Issue by doismellburning** [scholrly/neo4django#90]
When I attempt to `save()` a new `NodeModel` I get `IOError: [Errno 2] No such file or directory: '/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/gremlin/library.groovy'` - full traceback:

```
$ python stackcompare/manage.py shell
Python 2.7.1 (r271:86832, Jun 25 2011, 05:09:01)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from main.models import *
>>> s = StackExchangeUser()
>>> s.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/db/models/base.py", line 321, in save
    return super(NodeModel, self).save(using=using, **kwargs)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/db/models/base.py", line 336, in save_base
    self._save_neo4j_node(using)
  File "<string>", line 2, in _save_neo4j_node
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/db/models/base.py", line 115, in trans_method
    ret = func(*args, **kw)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/db/models/base.py", line 366, in _save_neo4j_node
    typesToIndex=type_names_to_index)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/neo4jclient.py", line 153, in gremlin_tx
    return self.gremlin(script, tx=True, **params)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/neo4jclient.py", line 145, in gremlin
    lib_script = include_all_libraries(lib_script)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/neo4jclient.py", line 124, in include_all_libraries
    return include_main_library(s)
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/neo4jclient.py", line 109, in include_main_library
    'gremlin/library.groovy').read()
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 888, in resource_stream
    self, resource_name
  File "/Users/kristian/git/stackcompare/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1285, in get_resource_stream
    return open(self._fn(self.module_path, resource_name), 'rb')
IOError: [Errno 2] No such file or directory: '/Users/kristian/git/stackcompare/lib/python2.7/site-packages/neo4django/gremlin/library.groovy'
>>>
```

Should https://github.com/scholrly/neo4django/blob/master/setup.py#L11 include `neo4django.gremlin` or am I misunderstanding things? 

I'm using 0.1.5

**Comment by mhluongo** [comment]
Intuitively it does seem that way- I'm exploring how I've never seen this issue before...

**Comment by doismellburning** [comment]
This is what I don't understand; if I'm not doing anything wrong, I can't see how no-one using this hasn't experienced the issue. Obviously tests won't pick this up, as they don't operate on the package, but users should...!

**Comment by mhluongo** [comment]
We (and most of the users I talk to) install from GitHub, so I wonder if that has anything to do with it...

**Comment by doismellburning** [comment]
Right, yes, if I install `neo4django` like so:

```
pip install -e git+git://github.com/scholrly/neo4django.git#egg=neo4django
```

then everything works just fine. If I `pip install neo4django` or `pip install git+git://github.com/scholrly/neo4django.git` then I get the original problem - thanks for the help, pull-request incoming!

**Comment by mhluongo** [comment]
Thank you sir! Next major release I'll try to come up with a convenient way to test the PyPi release =/

**Comment by mhluongo** [comment]
Oh, and while I'm thinking of it- if you're still on 0.1.5, consider upgrading :) I'll push this fix back to 0.1.5 on PyPi.

**Comment by doismellburning** [comment]
Yes I'm 'still on' [the latest PyPi package](http://pypi.python.org/pypi/neo4django)... :P

**Comment by mhluongo** [comment]
That... is a very good point, haha. I wanted to wait until there were more feature improvements, but maybe once these two regression tests are fixed 0.1.6 should be released. Hm...

**Comment by doismellburning** [comment]
Well now I can start using neo4django, I'll probably have more pull requests coming soon. Meanwhile I'd really appreciate it if you could get 0.1.5.1 on PyPi please :) (assuming that's "0.1.5 + this fix"). Thanks :)

**Comment by mhluongo** [comment]
Reopened because some things are looking fishy- I think we might be going too fast.

https://github.com/scholrly/neo4django/tree/54f24cf1b12425fa27634a114eeb9d4b01bd612d (tagged v0.1.5) doesn't even have a gremlin package- are you sure you're running in a clean environment? Or did I just exclude a huge piece of code until a later commit?

Exploring further.

**Comment by mhluongo** [comment]
Yeah, this traceback must be in a dirty environment- for example, if you download the 0.1.5 release from PyPi as a tarball and check, some of these modules in the traceback (eg, neo4jclient.py) weren't introduced yet. 0.1.5 was before the big gremlin-izing push, so that makes sense.

Could you have conflicting packages on your path?

**Comment by doismellburning** [comment]
You're right - I think I must have dirtied my environment while sorting something else (possibly Travis integration); I'm really sorry for wasting your time with that!

II believe this is still an issue for post-0.1.5 though, but yeah, I was definitely not looking at 0.1.5 at the time, sorry about that!

**Comment by mhluongo** [comment]
No worries, we definitely needed the setup.py edits anyway :)
