### ISSUE TITLE
Needs to be implemented: filter method

### ISSUE THREAD

**Issue by wcbeard** [scholrly/neo4django#91]
```
>>> p = list(Poll.objects.all())[1]
>>> list(p.choices.all())
 [<Choice: Corbin>, <Choice: Matt>, <Choice: Chris>]
>>> list(p.choices.all())[2].votes
1000
>>> p.choices.filter(votes__gt=3)
AttributeError: 'RelationshipQuerySet' object has no attribute 'filter'
```

The models are supposed to replicate the Poll and Choice models from the [Django tutorial](https://docs.djangoproject.com/en/1.4/intro/tutorial01/). The model definitions are [here](https://gist.github.com/2858702).

**Comment by mhluongo** [comment]
This should be able to reuse some of the machinery in query.py- in particular, the kwarg parsing and the Python-side filtering. Server-side filtering can also come from query.py, though maybe we shouldn't do that quite yet.
